name: Hardhat Deploy&Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Create local node and deploy
        run: |
          npx hardhat node &
          npx hardhat run scripts/deploy.ts --network localhost
      - name: Run Tests
        run: npx hardhat test