name: Project Build&Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install packages
        run: npm i
      - name: Create local node and deploy
        run: npm run -w solidity deploy.local
      - name: Run Tests
        run: npm run -w solidity test